"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import final

@final
class InvalidEmailError(Exception):
    def __init__(self, invalid_emails: list[str]) -> None:
        ...
    


@final
class LocationNotFoundError(Exception):
    def __init__(self, location: str) -> None:
        ...
    


@final
class InvalidUrlError(Exception):
    def __init__(self, url: str) -> None:
        ...
    


@final
class InvalidAttachementsError(Exception):
    def __init__(self, invalid_attachements: list[Path]) -> None:
        ...
    


@final
class ParserNotLoadedError(Exception):
    def __init__(self) -> None:
        ...
    


