"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from collections.abc import Sequence
from typing import override
from .inner import CalendarEvent, CalendarReminder

class Parser(ABC):
    def __init__(self) -> None:
        ...
    
    @abstractmethod
    @staticmethod
    def parse(unparsed_data: object) -> object:
        ...
    
    @abstractmethod
    @staticmethod
    def batch_parse(list_of_unparsed_data: Sequence[object]) -> Sequence[object]:
        ...
    


class ReminderParser(Parser, ABC):
    def __init__(self) -> None:
        ...
    
    @abstractmethod
    @staticmethod
    @override
    def parse(unparsed_data: object) -> CalendarReminder:
        ...
    
    @abstractmethod
    @staticmethod
    @override
    def batch_parse(list_of_unparsed_data: Sequence[object]) -> Sequence[CalendarReminder]:
        ...
    


class EventParser(Parser, ABC):
    def __init__(self) -> None:
        ...
    
    @abstractmethod
    @staticmethod
    @override
    def parse(unparsed_data: object) -> CalendarEvent:
        ...
    
    @abstractmethod
    @staticmethod
    @override
    def batch_parse(list_of_unparsed_data: Sequence[object]) -> Sequence[CalendarEvent]:
        ...
    


