"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from .inner import CalendarEvent, CalendarReminder
from .parsers import EventParser, ReminderParser

class Calendar(ABC):
    def __init__(self, source: str | None = ..., event_parser: EventParser | None = ..., reminder_parser: ReminderParser | None = ...) -> None:
        ...
    
    @abstractmethod
    def authentificate(self) -> None:
        ...
    
    @abstractmethod
    def is_authentificated(self) -> bool:
        ...
    
    def sync_calendar(self) -> None:
        ...
    
    @abstractmethod
    def pull_calendar(self) -> None:
        ...
    
    @abstractmethod
    def push_calendar(self) -> None:
        ...
    
    def sync_reminders(self) -> None:
        ...
    
    @abstractmethod
    def pull_reminders(self) -> None:
        ...
    
    @abstractmethod
    def push_reminders(self) -> None:
        ...
    
    def sync_all(self) -> None:
        ...
    
    def pull_all(self) -> None:
        ...
    
    def push_all(self) -> None:
        ...
    
    @_event_parser.setter
    def load_event_parser(self, parser: EventParser) -> None:
        ...
    
    @_reminder_parser.setter
    def load_reminder_parser(self, parser: ReminderParser) -> None:
        ...
    
    def add_event(self, event: CalendarEvent | object) -> None:
        ...
    
    def add_reminder(self, event: CalendarReminder | object) -> None:
        ...
    


