"""
This type stub file was generated by pyright.
"""

from .options import CalendarEventOptions, CalendarReminderOptions

class CalendarEvent:
    def __init__(self, options: CalendarEventOptions) -> None:
        ...
    


class CalendarReminder:
    def __init__(self, options: CalendarReminderOptions) -> None:
        ...
    


